### ISSUE TITLE
Issue is closed right after creation..

### ISSUE THREAD

**Issue by milewski** [alstr/todo-to-issue-action#50]
I have this issue where the action does detect the TODO and create the issue.. and close it right after referencing the same commit that created it...

![image](https://user-images.githubusercontent.com/2874967/123044646-89c57200-d42c-11eb-8b12-f6b20c4af25b.png)

![image](https://user-images.githubusercontent.com/2874967/123044798-baa5a700-d42c-11eb-962d-6ef63ae87363.png)

**Comment by alstr** [comment]
Hi, that's strange.

I take it the issue was created in `dab1adc`? Please could you take a screenshot of the diff showing any additions/deletions of TODOs? Thanks.

**Comment by milewski** [comment]
This is the diff of `dab1adc`

![image](https://user-images.githubusercontent.com/2874967/123054808-d2cef380-d437-11eb-8e18-a39e1600a735.png)

**Comment by milewski** [comment]
I think maybe it has something to do with the triggers being set to push and pull request ... because when this happens the action run twice ... I merged the PR and now new Todo looks fine...

**Comment by alstr** [comment]
Hmm, I'm still not entirely sure. I take it there were no other TODOs in the diff, one that was removed?

Setting it to run on push and pull could result in it running twice. You may want to fine tune it with some of the options described [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions).

Even if it ran twice, I don't know why the TODO was closed immediately after. The only time it should do that is when it appears in the diff as a deletion. I'll look into it some more.

**Comment by milewski** [comment]
There were some other changes on the to-do on the same PR.. like changing `/**` to `/*`  but other than this there was no commit that would remove it entirely and later add it back again...

**Comment by alstr** [comment]
If you change the TODO there is a chance that the old one will show in the diff as a deletion and the new one an addition. In theory that would close the old one and open a new one. If you can share more from the diff that would be useful, but I'll look into it anyway. Thanks.

**Comment by alstr** [comment]
I'm going to close this but if further information comes to light that you want to share, feel free. I've opened a couple of separate issues to look into improving the way the TODO extraction works (#62, #63).
